# Generated by Django 3.2.7 on 2021-09-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_header', models.CharField(max_length=60)),
                ('article_description', models.CharField(max_length=300)),
                ('first_header', models.CharField(max_length=40)),
                ('first_description', models.CharField(max_length=300)),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('second_header', models.CharField(max_length=40)),
                ('second_description', models.CharField(max_length=300)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('third_header', models.CharField(max_length=40)),
                ('third_description', models.CharField(max_length=300)),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('fourth_header', models.CharField(max_length=40)),
                ('fourth_description', models.CharField(max_length=300)),
                ('fourth_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('fifth_header', models.CharField(max_length=40)),
                ('fifth_description', models.CharField(max_length=300)),
                ('fifth_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sixth_header', models.CharField(max_length=40)),
                ('sixth_description', models.CharField(max_length=300)),
                ('sixth_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('seventh_header', models.CharField(max_length=40)),
                ('seventh_description', models.CharField(max_length=300)),
                ('seventh_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('eighth_header', models.CharField(max_length=40)),
                ('eighth_description', models.CharField(max_length=300)),
                ('eighth_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ninth_header', models.CharField(max_length=40)),
                ('ninth_description', models.CharField(max_length=300)),
                ('ninth_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tenth_header', models.CharField(max_length=40)),
                ('tenth_description', models.CharField(max_length=300)),
                ('tenth_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
