# Generated by Django 3.2.7 on 2021-09-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='article_banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
