# Generated by Django 3.2.7 on 2021-09-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_article_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='static_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
